config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'lists#index'
  resources :lists

  post 'add_favorites', to: 'lists#add_favorite'
  delete 'remove_favorites', to: 'lists#remove_favorite'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :user
    has_many :users, through: :favorites
    has_many :favorites
    has_many :tasks
    accepts_nested_attributes_for :tasks
    validates :title, presence: true, 
    uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
  has_many :favorites
  has_many :lists, through: :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
        @lists = List.all
    end
    
    def show
        @list = List.find(params[:id])
    end

    def new
        @list = List.new()
    end

    def edit
        @list = List.find(params[:id])
    end

    def create
        @list = current_user.lists.build(list_params)
        @list.user = current_user
        p "@list, #{@list.inspect}"
        if @list.save
            redirect_to lists_path
        else
            render 'new'
        end
    end

    def update
        @list = List.find(params[:id])
        if @list.update(list_params)
            redirect_to lists_path
            #TO-DO "renderizar edit com mensagem de sucesso"
        else
            render 'edit'
        end
    end

    def destroy
        @list = List.find(params[:id])
        @list.destroy
        redirect_to lists_path
    end

    def add_favorite
        Favorite.create(list_id: params[:list_id], user: current_user)
        redirect_to list_path(params[:list_id])
    end

    def remove_favorite
        Favorite.find_by(list_id: params[:list_id], user: current_user).destroy
        redirect_to list_path(params[:list_id])
    end

private
    def list_params
        params.require(:list).permit(:title, :public)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <% if user_signed_in? %>
        You are signed in as <%= current_user.email %>
        <%= link_to "Sign Out", destroy_user_session_path, {method: :delete, class: "nav-link pull-right"} %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, {class: "nav-link pull-right"} %>
        <%= link_to "Sign In", new_user_session_path, {class: "nav-link pull-right"} %>
      <% end %>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container-fluid"> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Lists", lists_path() %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @list.title %></li>
  </ol>
</nav>

<h3>Edit list</h3>
 
<%= form_with(model: @list, local: true) do |form| %>
    <% if @list.errors.any? %>
        <div id="error_explanation">
        <h2>
            <%= pluralize(@list.errors.count, "error") %> preveniu a lista de ser salva:
        </h2>
        <ul>
            <% @list.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <%= form.label :title %><br>
                <%= form.text_field :title, {class: "form-control"} %>
            </div>
            <div class="form-check">
                <%= form.check_box :public, {class: "form-check-input"} %>
                <%= form.label :public, {class: "form-check-label"} %><br>
            </div>
            <%= form.submit 'Submit', {class: "btn btn-primary"} %>
            <% if current_user == @list.user %>
                <%= link_to 'Delete', list_path(@list),
                    class: "btn btn-danger",
                    method: :delete,
                    data: {confirm: "Are you sure?"} %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/lists/index.html.erb
<h1>Lists</h1>
<% if user_signed_in? %>
  <h2>My Lists</h2>
  <% @lists.each do |list| %>
    <% if current_user == list.user %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= link_to list.title, list_path(list) %></h5>
      </div>
    </div>
    <% end %>
  <% end %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= link_to fa_icon("plus-square"), new_list_path() %></h5>
    </div>
  </div>
<% end %>

  <h2>Public Lists</h2>
  <% @lists.each do |list| %>
    <% if list.public %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= link_to list.title, list_path(list) %></h5>
        </div>
      </div>
    <% end %>
  <% end %>

  <h2>Favorite Lists</h2>
  <% @lists.each do |list| %>
    <% if Favorite.find_by(list_id: list.id, user: current_user) %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= link_to list.title, list_path(list) %></h5>
        </div>
      </div>
    <% end %>
  <% end %>

app/views/lists/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Lists", lists_path() %></li>
    <li class="breadcrumb-item active" aria-current="page">New List</li>
  </ol>
</nav>

<h3>New list</h3>

<%= form_with scope: :list, url: lists_path, local: true do |form| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@list.errors.count, "error") %> preveniu a lista de ser salva:
      </h2>
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %><br>
        <%= form.text_field :title, {class: "form-control"} %>
      </div>
      <div class="form-check">
        <%= form.check_box :public, {class: "form-check-input"} %>
        <%= form.label :public, {class: "form-check-label"} %><br>
      </div>
      <%= form.submit 'Submit', {class: "btn btn-primary"} %>
    </div>
  </div>
<% end %>

app/views/lists/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Lists", lists_path() %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @list.title %></li>
  </ol>
</nav>

<h3>Show list</h3>

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
        <label for="list_title">Title</label><br>
        <input class="form-control" disabled type="text" name="list[title]" id="list_title" value="<%=@list.title%>">
        </div>
    </div>
</div>


<% if user_signed_in? %>
    <% if Favorite.find_by(list_id: @list.id, user: current_user) %>
        <%= button_to remove_favorites_path({list_id: @list.id}), {method: :delete, class: "btn btn-secondary"} do %>
            <%= fa_icon("star") %> Remove from favorites
        <% end %>
    <% else %>
        <%= button_to add_favorites_path({list_id: @list.id}), {method: :post, class: "btn btn-secondary"} do %>
            <%= fa_icon("star") %> Add to favorites
        <% end %>
    <% end %>
<% end %>
<br>
<% if current_user == @list.user %>
    <%= link_to "Edit", edit_list_path(), {class: "btn btn-secondary"} %>
    <%= link_to 'Delete', list_path(@list),
    class: "btn btn-danger",
    method: :delete,
    data: {confirm: "Are you sure?"} %>
<% end %>